# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HllK1UOqiLU1WRYfefFW972eeheRfj8sTCTdkwzqYsFfTCyioG8OLiSx7Z2HOVxyMCX6r8UQqPY9CrP3EjhhIZGrs4Y1k8C8wh5vR0azOiQIwfmGzl+BH0zjj2JQW9deQxYS8m5rHavyLFb7rqFVM8+iXxpLtUss7QkCk2Izfq/yOY0Y8C/2q0g1Pk8a5CWaniZpRqllJtFINbfJCnsnP85jf4kRy+JtwX4uv1duVucX12n4VTNjNYEXoWqb79OnKBMiAdtSuyWtAaC8jbOVi+wSWik29FgwW0UT7JWFWPTfvSu9R5sE+8R13eEjXYKjdcJ/CZj6IECEG9tCqZ5TG0wofOJ5CT77vUc5zAgXTMjcfAj3zf+WnQBE9loTHY+WODTjHAXsKFDp/MKtRGbLnzrYZ9YMYFUjKjGgRIYoMcBfmVszlfSnrGzYhsMZ6TuxStF2xgjAxBUBiEOHT5NfdrLOg1g+kkbgnYgfWZMVf/C5LzpGv1SSIi+xu0MYlcaf9rFDTN1BHJ5PQTYt5/cBYurQPfn4ujRtt7tAdTWp4/DMxR3I7xZ+6vcgmNVGxjpQtN7dpZZuh33PBKLsYtFoJ3UGBQqhogZ4HLS/Ea/92JBoAbDMhnFhdd4x7NsOaW82v3orFfobK43i80AIoZBI0Ccj3JS5hk073ul1fKXMDg0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi