# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "a2OIx3dUbjZKdAJy7aNn5KK11qi+Eo411ACJqWZm7GsMl6tSbO2UBlI8RhSDgd8O3Qz8fznLGa8LUFPisuvyK35Opxl3Jql6i0L38HgPduzhxlgunLekj/Z3+vfdWqPWSAHOK01FCOomSHxiTX+o8giIrDN29iRl1fQvqOmykGRFpQjDLjg1yR352PN22KWSsdHNJ1jJZXe+os8EYDDKhKl/fd7nMggtQhAXtFufBecDHG4cEkMULFIx2qjWbyVMCk/TGIya3V5L0hUeKd93parzE8TX71Q7cXIOQixn5yvZXebGGgNwowxpBHsrhTFcapJnOA0f0MY2GNP+2qLfYsVo9Vlk6BTtNCW1vAnWnz01ifv/CWRwAHKXCfrNLxVlpLHWNqxOxio9rHRdnkjEA+rsJrKv1VtbT1y1rLSMJVZk2FBtUId398lCvp8WU3azVnoK+ZKhhLehNKeXxJxk4PpjJdYTFTqBTfT2IVHyU52JKkKJneBshtaf4c4tYqk7jQG3ODLbjbEkH9QlM8JbtyqJCSipQhJdKpKKeeATaRH1ysVdClHdm02jWJ/sJeeeEbI/ICeFscP4h7BHNQvkQo8jgu6BM43Rg0vGzUibQsBD0VVuFUiH7+Vary2Tuy18K4i3tL8rBCfvRjMX0A76jDkan/evOg1PB3mLuowYf9Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
