appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: HllK1UOqiLU1WRYfefFW972eeheRfj8sTCTdkwzqYsFfTCyioG8OLiSx7Z2HOVxyMCX6r8UQqPY9CrP3EjhhIZGrs4Y1k8C8wh5vR0azOiQIwfmGzl+BH0zjj2JQW9deQxYS8m5rHavyLFb7rqFVM8+iXxpLtUss7QkCk2Izfq/yOY0Y8C/2q0g1Pk8a5CWaniZpRqllJtFINbfJCnsnP85jf4kRy+JtwX4uv1duVucX12n4VTNjNYEXoWqb79OnKBMiAdtSuyWtAaC8jbOVi+wSWik29FgwW0UT7JWFWPTfvSu9R5sE+8R13eEjXYKjdcJ/CZj6IECEG9tCqZ5TG0wofOJ5CT77vUc5zAgXTMjcfAj3zf+WnQBE9loTHY+WODTjHAXsKFDp/MKtRGbLnzrYZ9YMYFUjKjGgRIYoMcBfmVszlfSnrGzYhsMZ6TuxStF2xgjAxBUBiEOHT5NfdrLOg1g+kkbgnYgfWZMVf/C5LzpGv1SSIi+xu0MYlcaf9rFDTN1BHJ5PQTYt5/cBYurQPfn4ujRtt7tAdTWp4/DMxR3I7xZ+6vcgmNVGxjpQtN7dpZZuh33PBKLsYtFoJ3UGBQqhogZ4HLS/Ea/92JBoAbDMhnFhdd4x7NsOaW82v3orFfobK43i80AIoZBI0Ccj3JS5hk073ul1fKXMDg0=}
bot:
  automerge: true
